import React, { useState } from 'react';
import { createClient } from '@supabase/supabase-js';

// Supabase Configuration
// IMPORTANT: For local development with Parcel, ensure your .env variables are prefixed with PARCEL_
// e.g., PARCEL_SUPABASE_URL="YOUR_SUPABASE_URL"
// For Vercel deployment, you set SUPABASE_URL and SUPABASE_ANON_KEY directly in Vercel's environment variables (without PARCEL_ prefix).
// This line tries to get the variable with PARCEL_ prefix (for local) or without (for Vercel).
const SUPABASE_URL = process.env.PARCEL_SUPABASE_URL || process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.PARCEL_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY;

// Initialize Supabase client
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// --- DEBUGGING AID: Log Supabase URLs ---
// Check your browser's console (F12) after running 'pnpm run dev' to see these values.
console.log('Supabase URL (resolved):', SUPABASE_URL);
console.log('Supabase Anon Key (resolved, first few chars):', SUPABASE_ANON_KEY ? SUPABASE_ANON_KEY.substring(0, 5) + '...' : 'Not set');
// --- END DEBUGGING AID ---


// Simple English to Urdu dictionary for demonstration (Re-added as per project features)
const englishToUrduDictionary = {
  "hello": "ہیلو",
  "world": "دنیا",
  "summary": "خلاصہ",
  "blog": "بلاگ",
  "post": "پوسٹ",
  "web": "ویب",
  "scraping": "اسکریپنگ",
  "data": "ڈیٹا",
  "extraction": "نکالنا",
  "used": "استعمال کیا جاتا ہے",
  "for": "کے لیے",
  "from": "سے",
  "websites": "ویب سائٹس",
  "the": "کے",
  "is": "ہے",
  "a": "ایک",
  "or": "یا",
  "and": "اور",
  "this": "یہ",
  "article": "مضمون",
  "needs": "ضرورت ہے",
  "additional": "اضافی",
  "citations": "حوالے",
  "verification": "تصدیق",
  "please": "براہ مہربانی",
  "help": "مدد کریں",
  "improve": "بہتر بنائیں",
  "by": "کے ذریعہ",
  "adding": "شامل کرنا",
  "to": "کو",
  "reliable": "قابل اعتماد",
  "sources": "ذرائع",
  "it": "یہ",
  "is": "ہے",
  "a": "ایک",
  "form": "شکل",
  "of": "کا",
  "copying": "کاپی کرنا",
  "in": "میں",
  "which": "جس میں",
  "specific": "مخصوص",
  "gathered": "جمع کیا جاتا ہے",
  "copied": "کاپی کیا جاتا ہے",
  "typically": "عام طور پر",
  "into": "میں",
  "central": "مرکزی",
  "local": "مقامی",
  "database": "ڈیٹا بیس",
  "spreadsheet": "اسپریڈ شیٹ",
  "later": "بعد میں",
  "retrieval": "بازیافت",
  "analysis": "تجزیہ",
  "involves": "شامل ہے",
  "fetching": "حاصل کرنا",
  "then": "پھر",
  "extracting": "نکالنا",
  "from": "سے",
  "page": "صفحہ",
  "browser": "براؤزر",
  "does": "کرتا ہے",
  "when": "جب",
  "user": "صارف",
  "views": "دیکھتا ہے",
  "therefore": "لہذا",
  "main": "اہم",
  "component": "جز",
  "processing": "پروسیسنگ",
  "having": "ہونے کے بعد",
  "can": "سکتا ہے",
  "take": "لے",
  "place": "جگہ",
  "content": "مواد",
  "may": "سکتا ہے",
  "parsed": "پارس کیا جا سکتا ہے",
  "searched": "تلاش کیا جا سکتا ہے",
  "reformatted": "دوبارہ فارمیٹ کیا جا سکتا ہے",
  "its": "اس کے",
  "loaded": "لوڈ کیا جا سکتا ہے",
  "scrapers": "اسکریپرز",
  "something": "کچھ",
  "out": "باہر",
  "make": "بنانا",
  "use": "استعمال",
  "another": "دوسرے",
  "purpose": "مقصد",
  "somewhere": "کہیں",
  "else": "اور",
  "example": "مثال",
  "would": "ہوگا",
  "be": "ہو",
  "finding": "تلاش کرنا",
  "copying": "کاپی کرنا",
  "names": "نام",
  "telephone": "ٹیلی فون",
  "numbers": "نمبر",
  "companies": "کمپنیاں",
  "their": "ان کے",
  "urls": "یو آر ایل",
  "e-mail": "ای میل",
  "addresses": "پتوں",
  "list": "فہرست",
  "contact": "رابطہ",
  "also": "بھی",
  "used": "استعمال کیا جاتا ہے",
  "as": "بطور",
  "applications": "ایپلی کیشنز",
  "web": "ویب",
  "indexing": "انڈیکسنگ",
  "mining": "مائننگ",
  "data": "ڈیٹا",
  "online": "آن لائن",
  "price": "قیمت",
  "change": "تبدیلی",
  "monitoring": "مانیٹرنگ",
  "comparison": "موازنہ",
  "product": "پروڈکٹ",
  "review": "جائزہ",
  "gathering": "جمع کرنا",
  "real": "حقیقی",
  "estate": "اسٹیٹ",
  "listings": "فہرستیں",
  "weather": "موسم",
  "tracking": "ٹریکنگ",
  "presence": "موجودگی",
  "reputation": "شہرت",
  "mashup": "میش اپ",
  "integration": "انضمام",
  "pages": "صفحات",
  "built": "بنائے گئے ہیں",
  "using": "استعمال کرتے ہوئے",
  "text-based": "متن پر مبنی",
  "mark-up": "مارک اپ",
  "languages": "زبانیں",
  "frequently": "اکثر",
  "contain": "پر مشتمل ہوتے ہیں",
  "wealth": "دولت",
  "useful": "مفید",
  "form": "شکل",
  "however": "تاہم",
  "most": "زیادہ تر",
  "designed": "ڈیزائن کیے گئے ہیں",
  "human": "انسانی",
  "end-users": "آخری صارفین",
  "not": "نہیں",
  "ease": "آسانی",
  "automated": "خودکار",
  "result": "نتیجہ",
  "specialized": "خصوصی",
  "tools": "اوزار",
  "software": "سافٹ ویئر",
  "developed": "تیار کیے گئے ہیں",
  "facilitate": "آسان بنانا",
  "include": "شامل ہیں",
  "market": "مارکیٹ",
  "businesses": "کاروبار",
  "rely": "انحصار کرتے ہیں",
  "services": "خدمات",
  "efficiently": "موثر طریقے سے",
  "utilize": "استعمال کریں",
  "newer": "نئے",
  "forms": "اقسام",
  "involve": "شامل ہیں",
  "monitoring": "مانیٹرنگ",
  "feeds": "فیڈز",
  "servers": "سرورز",
  "example": "مثال کے طور پر",
  "json": "JSON",
  "commonly": "عام طور پر",
  "transport": "ٹرانسپورٹ",
  "mechanism": "میکانزم",
  "between": "کے درمیان",
  "client": "کلائنٹ",
  "methods": "طریقے",
  "some": "کچھ",
  "prevent": "روکنا",
  "detecting": "پتہ لگانا",
  "disallowing": "اجازت نہ دینا",
  "bots": "بوٹس",
  "crawling": "کرالنگ",
  "viewing": "دیکھنا",
  "response": "جواب میں",
  "systems": "سسٹم",
  "techniques": "تکنیکیں",
  "dom": "DOM",
  "parsing": "پارسن",
  "computer": "کمپیوٹر",
  "vision": "ویژن",
  "natural": "قدرتی",
  "language": "زبان",
  "processing": "پروسیسنگ",
  "simulate": "نقالی کرنا",
  "browsing": "براؤزنگ",
  "enable": "قابل بنانا",
  "gathering": "جمع کرنا",
  "offline": "آف لائن",
  "history": "تاریخ",
  "after": "کے بعد",
  "birth": "پیدائش",
  "world": "دنیا",
  "wide": "وسیع",
  "web": "ویب",
  "1989": "1989",
  "first": "پہلا",
  "robot": "روبوٹ",
  "1993": "1993",
  "june": "جون",
  "intended": "مقصد تھا",
  "only": "صرف",
  "measure": "پیمائش کرنا",
  "size": "سائز",
  "december": "دسمبر",
  "crawler-based": "کرالر پر مبنی",
  "search": "تلاش",
  "engine": "انجن",
  "launched": "لانچ کیا گیا",
  "fewer": "کم",
  "available": "دستیاب",
  "rely": "انحصار کرتے تھے",
  "human": "انسانی",
  "administrators": "ایڈمنسٹریٹرز",
  "collect": "جمع کرنا",
  "format": "فارمیٹ کرنا",
  "links": "لنکس",
  "comparison": "موازنہ میں",
  "jump": "جمپ",
  "station": "اسٹیشن",
  "2000": "2000",
  "api": "API",
  "created": "تخلیق کیا گیا",
  "application": "ایپلیکیشن",
  "programming": "پروگرامنگ",
  "interface": "انٹرفیس",
  "makes": "بناتی ہے",
  "much": "بہت",
  "easier": "آسان",
  "develop": "تیار کرنا",
  "program": "پروگرام",
  "providing": "فراہم کر کے",
  "building": "بلڈنگ",
  "blocks": "بلاکس",
  "salesforce": "سیلزفورس",
  "ebay": "ای بے",
  "their": "ان کا",
  "own": "اپنا",
  "programmers": "پروگرامرز",
  "access": "رسائی",
  "download": "ڈاؤن لوڈ",
  "some": "کچھ",
  "public": "عوام",
  "since": "تب سے",
  "many": "بہت سے",
  "offer": "پیش کرتے ہیں",
  "people": "لوگوں",
  "database": "ڈیٹا بیس",
  "field": "میدان",
  "active": "فعال",
  "developments": "ترقیات",
  "sharing": "شیئر کرنا",
  "common": "مشترکہ",
  "goal": "مقصد",
  "semantic": "سیمینٹک",
  "vision": "ویژن",
  "ambitious": "پرمعزم",
  "initiative": "پہل",
  "still": "اب بھی",
  "requires": "ضرورت ہے",
  "breakthroughs": "پیش رفت",
  "text": "متن",
  "understanding": "سمجھ",
  "artificial": "مصنوعی",
  "intelligence": "ذہانت",
  "human-computer": "انسانی کمپیوٹر",
  "interactions": "بات چیت",
  "simplest": "سب سے آسان",
  "form": "شکل",
  "manually": "دستی طور پر",
  "copying": "کاپی کرنا",
  "pasting": "پیسٹ کرنا",
  "into": "میں",
  "file": "فائل",
  "sometimes": "کبھی کبھی",
  "even": "یہاں تک کہ",
  "best": "بہترین",
  "technology": "ٹیکنالوجی",
  "cannot": "نہیں کر سکتی",
  "replace": "تبدیل کرنا",
  "manual": "دستی",
  "examination": "جانچ",
  "only": "صرف",
  "workable": "قابل عمل",
  "solution": "حل",
  "explicitly": "واضح طور پر",
  "set": "سیٹ",
  "up": "کرنا",
  "barriers": "رکاوٹیں",
  "prevent": "روکنا",
  "machine": "مشین",
  "automation": "آٹومیشن",
  "pattern": "پیٹرن",
  "matching": "میچنگ",
  "powerful": "طاقتور",
  "approach": "طریقہ",
  "extract": "نکالنا",
  "information": "معلومات",
  "can": "سکتا ہے",
  "based": "پر مبنی",
  "unix": "یونیکس",
  "grep": "grep",
  "command": "کمانڈ",
  "regular": "باقاعدہ",
  "expression-matching": "ایکسپریشن میچنگ",
  "facilities": "سہولیات",
  "programming": "پروگرامنگ",
  "languages": "زبانوں",
  "for": "کے لیے",
  "instance": "مثال",
  "perl": "پیرل",
  "python": "پائتھن",
  "http": "HTTP",
  "static": "جامد",
  "dynamic": "متحرک",
  "retrieved": "حاصل کیا جا سکتا ہے",
  "posting": "پوسٹ کر کے",
  "requests": "درخواستیں",
  "remote": "ریموٹ",
  "socket": "ساکٹ",
  "many": "بہت سی",
  "large": "بڑی",
  "collections": "کلیکشنز",
  "pages": "صفحات",
  "generated": "تیار کیے گئے ہیں",
  "underlying": "بنیادی",
  "structured": "ساختہ",
  "source": "ماخذ",
  "like": "جیسے",
  "database": "ڈیٹا بیس",
  "category": "قسم",
  "typically": "عام طور پر",
  "encoded": "انکوڈ کیے جاتے ہیں",
  "similar": "ملتے جلتے",
  "common": "مشترکہ",
  "script": "اسکرپٹ",
  "template": "ٹیمپلیٹ",
  "data": "ڈیٹا",
  "mining": "مائننگ",
  "program": "پروگرام",
  "detects": "پتہ لگاتا ہے",
  "such": "ایسے",
  "templates": "ٹیمپلیٹس",
  "particular": "خاص",
  "information": "معلومات",
  "translates": "ترجمہ کرتا ہے",
  "relational": "رشتہ دار",
  "form": "شکل",
  "called": "کہلاتا ہے",
  "wrapper": "ریپر",
  "generation": "جنریشن",
  "algorithms": "الگورتھم",
  "assume": "فرض کرتے ہیں",
  "input": "ان پٹ",
  "pages": "صفحات",
  "induction": "انڈکشن",
  "system": "سسٹم",
  "conform": "مطابق ہوتے ہیں",
  "scheme": "اسکیم",
  "moreover": "مزید برآں",
  "semi-structured": "نیم ساختہ",
  "query": "سوال",
  "languages": "زبانیں",
  "xquery": "XQuery",
  "htql": "HTQL",
  "used": "استعمال کی جا سکتی ہیں",
  "parse": "پارسن",
  "retrieve": "حاصل کرنا",
  "transform": "تبدیل کرنا",
  "document": "دستاویز",
  "object": "آبجیکٹ",
  "model": "ماڈل",
  "using": "استعمال کرتے ہوئے",
  "selenium": "سیلینیم",
  "playwright": "پلے رائٹ",
  "developers": "ڈویلپرز",
  "control": "کنٹرول کر سکتے ہیں",
  "web": "ویب",
  "browser": "براؤزر",
  "chrome": "کروم",
  "firefox": "فائر فاکس",
  "wherein": "جس میں",
  "load": "لوڈ",
  "navigate": "نیویگیٹ",
  "retrieve": "حاصل",
  "data": "ڈیٹا",
  "websites": "ویب سائٹس",
  "method": "طریقہ",
  "especially": "خاص طور پر",
  "useful": "مفید",
  "scraping": "اسکریپنگ",
  "dynamic": "متحرک",
  "sites": "سائٹس",
  "since": "چونکہ",
  "fully": "مکمل طور پر",
  "entire": "پورا",
  "accessed": "رسائی حاصل کی جا سکتی ہے",
  "parsed": "پارس کیا جا سکتا ہے",
  "expression": "ایکسپریشن",
  "language": "زبان",
  "xpath": "XPath",
  "vertical": "عمودی",
  "aggregation": "ایگریگیشن",
  "several": "کئی",
  "companies": "کمپنیوں",
  "developed": "تیار کی ہیں",
  "specific": "مخصوص",
  "harvesting": "ہارویسٹنگ",
  "platforms": "پلیٹ فارمز",
  "create": "تخلیق کرتے ہیں",
  "monitor": "مانیٹر کرتے ہیں",
  "multitude": "کثرت",
  "bots": "بوٹس",
  "no": "کوئی",
  "man": "آدمی",
  "loop": "لوپ",
  "direct": "براہ راست",
  "human": "انسانی",
  "involvement": "شمولیت",
  "work": "کام",
  "related": "متعلق",
  "target": "ہدف",
  "site": "سائٹ",
  "preparation": "تیاری",
  "involves": "شامل ہے",
  "establishing": "قائم کرنا",
  "knowledge": "علم",
  "base": "بیس",
  "entire": "پوری",
  "then": "پھر",
  "automatically": "خود بخود",
  "robustness": "مضبوطی",
  "measured": "پیمائش کی جاتی ہے",
  "quality": "معیار",
  "information": "معلومات",
  "retrieves": "حاصل کرتا ہے",
  "usually": "عام طور پر",
  "number": "تعداد",
  "fields": "فیلڈز",
  "scalability": "اسکیل ایبلٹی",
  "quick": "تیز",
  "scale": "اسکیل",
  "hundreds": "سینکڑوں",
  "thousands": "ہزاروں",
  "sites": "سائٹس",
  "mostly": "زیادہ تر",
  "used": "استعمال کیا جاتا ہے",
  "target": "ہدف بنانے کے لیے",
  "long": "لمبی",
  "tail": "ٹیل",
  "common": "عام",
  "aggregators": "ایگریگیٹرز",
  "find": "پاتے ہیں",
  "complicated": "پیچیدہ",
  "labor-intensive": "محنت طلب",
  "harvest": "حاصل کرنا",
  "content": "مواد",
  "semantic": "سیمینٹک",
  "annotation": "تشریح",
  "recognizing": "پہچاننا",
  "pages": "صفحات",
  "scraped": "اسکریپ کیے گئے",
  "embrace": "اپناتے ہیں",
  "metadata": "میٹا ڈیٹا",
  "markups": "مارک اپس",
  "annotations": "تشریحات",
  "which": "جو",
  "can": "سکتے ہیں",
  "locate": "تلاش کرنے کے لیے",
  "specific": "مخصوص",
  "data": "ڈیٹا",
  "snippets": "اسنیپٹس",
  "embedded": "ایمبیڈڈ",
  "microformat": "مائیکرو فارمیٹ",
  "does": "کرتا ہے",
  "technique": "تکنیک",
  "viewed": "دیکھا جا سکتا ہے",
  "special": "خاص",
  "case": "کیس",
  "dom": "DOM",
  "parsing": "پارسن",
  "another": "دوسرے",
  "organized": "منظم",
  "layer": "پرت",
  "stored": "ذخیرہ کیا جاتا ہے",
  "managed": "انتظام کیا جاتا ہے",
  "separately": "علیحدہ",
  "from": "سے",
  "web": "ویب",
  "pages": "صفحات",
  "so": "تاکہ",
  "scrapers": "اسکریپرز",
  "retrieve": "حاصل کر سکیں",
  "schema": "اسکیما",
  "instructions": "ہدایات",
  "before": "پہلے",
  "computer": "کمپیوٹر",
  "vision": "ویژن",
  "web-page": "ویب پیج",
  "analysis": "تجزیہ",
  "efforts": "کوششیں",
  "using": "استعمال کرتے ہوئے",
  "machine": "مشین",
  "learning": "لرننگ",
  "attempt": "کوشش کرتے ہیں",
  "identify": "شناخت کرنا",
  "extract": "نکالنا",
  "information": "معلومات",
  "interpreting": "تشریح کر کے",
  "visually": "بصری طور پر",
  "human": "انسانی",
  "being": "ہونے کے ناطے",
  "might": "سکتے ہیں",
  "ai-powered": "AI سے چلنے والا",
  "document": "دستاویز",
  "understanding": "سمجھ",
  "uses": "استعمال کرتا ہے",
  "advanced": "اعلی درجے کی",
  "ai": "AI",
  "interpret": "تشریح کرنا",
  "process": "پروسیس کرنا",
  "content": "مواد",
  "contextually": "سیاق و سباق کے مطابق",
  "extracting": "نکالنا",
  "relevant": "متعلقہ",
  "transforming": "تبدیل کرنا",
  "customizing": "اپنی مرضی کے مطابق بنانا",
  "outputs": "آؤٹ پٹ",
  "based": "پر مبنی",
  "structure": "ساخت",
  "meaning": "معنی",
  "enables": "قابل بناتا ہے",
  "more": "زیادہ",
  "intelligent": "ذہین",
  "flexible": "لچکدار",
  "extraction": "نکالنا",
  "accommodating": "مطابق بنانا",
  "complex": "پیچیدہ",
  "dynamic": "متحرک",
  "legal": "قانونی",
  "issues": "مسائل",
  "examples": "مثالیں",
  "perspective": "نقطہ نظر",
  "section": "سیکشن",
  "deal": "نمٹتے ہیں",
  "primarily": "بنیادی طور پر",
  "united": "متحدہ",
  "states": "ریاستیں",
  "represent": "نمائندگی کرتے ہیں",
  "worldwide": "دنیا بھر میں",
  "view": "نقطہ نظر",
  "subject": "موضوع",
  "improve": "بہتر بنائیں",
  "discuss": "بحث کریں",
  "talk": "بات چیت",
  "page": "صفحہ",
  "create": "تخلیق کریں",
  "new": "نیا",
  "appropriate": "مناسب",
  "october": "اکتوبر",
  "2015": "2015",
  "learn": "سیکھیں",
  "how": "کیسے",
  "when": "کب",
  "remove": "ہٹانا",
  "message": "پیغام",
  "legality": "قانونی حیثیت",
  "varies": "مختلف ہوتی ہے",
  "across": "بھر میں",
  "world": "دنیا",
  "general": "عام طور پر",
  "against": "کے خلاف",
  "terms": "شرائط",
  "service": "سروس",
  "some": "کچھ",
  "websites": "ویب سائٹس",
  "enforceability": "قابل نفاذ",
  "unclear": "واضح نہیں ہے",
  "owners": "مالکان",
  "use": "استعمال کر سکتے ہیں",
  "three": "تین",
  "major": "بڑے",
  "claims": "دعویٰ",
  "prevent": "روکنے کے لیے",
  "undesired": "ناپسندیدہ",
  "copyright": "کاپی رائٹ",
  "infringement": "خلاف ورزی",
  "compilation": "تالیف",
  "violation": "خلاف ورزی",
  "computer": "کمپیوٹر",
  "fraud": "دھوکہ دہی",
  "abuse": "بدسلوکی",
  "act": "ایکٹ",
  "trespass": "تجاوز",
  "chattel": "منقولہ جائیداد",
  "effectiveness": "تاثیر",
  "relies": "انحصار کرتی ہے",
  "upon": "پر",
  "meeting": "ملاقات",
  "various": "مختلف",
  "criteria": "معیار",
  "case": "کیس",
  "law": "قانون",
  "still": "اب بھی",
  "evolving": "ارتقاء پذیر",
  "example": "مثال کے طور پر",
  "regard": "کے حوالے سے",
  "outright": "مکمل",
  "duplication": "نقل",
  "original": "اصل",
  "expression": "اظہار",
  "many": "بہت سے",
  "illegal": "غیر قانونی",
  "courts": "عدالتوں",
  "ruled": "فیصلہ کیا",
  "feist": "Feist",
  "publications": "پبلیکیشنز",
  "rural": "دیہی",
  "telephone": "ٹیلی فون",
  "allowable": "قابل اجازت",
  "acknowledged": "تسلیم کیا ہے",
  "users": "صارفین",
  "scrapers": "اسکریپرز",
  "robots": "روبوٹس",
  "held": "قرار دیا جا سکتا ہے",
  "liable": "ذمہ دار",
  "committing": "کرنے کے لیے",
  "chattels": "منقولہ جائیداد",
  "involves": "شامل ہے",
  "system": "سسٹم",
  "itself": "خود",
  "considered": "سمجھا جاتا ہے",
  "personal": "ذاتی",
  "property": "جائیداد",
  "upon": "پر",
  "trespassing": "تجاوز کرنا",
  "best": "بہترین",
  "known": "معروف",
  "ebay": "ای بے",
  "bidder's": "بڈر کا",
  "edge": "ایڈج",
  "resulted": "نتیجہ نکلا",
  "injunction": "حکم امتناعی",
  "ordering": "حکم دینا",
  "stop": "روکنا",
  "accessing": "رسائی حاصل کرنا",
  "collecting": "جمع کرنا",
  "indexing": "انڈیکسنگ",
  "auctions": "نیلامیاں",
  "web": "ویب",
  "site": "سائٹ",
  "involved": "شامل تھا",
  "automatic": "خودکار",
  "placing": "رکھنا",
  "bids": "بولیاں",
  "auction": "نیلامی",
  "sniping": "اسنائپنگ",
  "however": "تاہم",
  "order": "حکم",
  "succeed": "کامیاب ہونا",
  "claim": "دعویٰ",
  "trespass": "تجاوز",
  "chattels": "منقولہ جائیداد",
  "plaintiff": "مدعی",
  "demonstrate": "ثابت کرنا",
  "defendant": "مدعا علیہ",
  "intentionally": "جان بوجھ کر",
  "without": "کے بغیر",
  "authorization": "اجازت",
  "interfered": "مداخلت کی",
  "possessory": "قبضہ کا",
  "interest": "مفاد",
  "caused": "کی وجہ سے ہوا",
  "damage": "نقصان",
  "not": "نہیں",
  "all": "تمام",
  "cases": "کیسز",
  "spidering": "اسپائیڈرنگ",
  "brought": "لائے گئے",
  "before": "کے سامنے",
  "courts": "عدالتوں",
  "considered": "سمجھا گیا",
  "one": "ایک",
  "first": "پہلے",
  "major": "بڑے",
  "tests": "ٹیسٹ",
  "screen": "اسکرین",
  "scraping": "اسکریپنگ",
  "involved": "شامل تھا",
  "american": "امریکن",
  "airlines": "ایئر لائنز",
  "firm": "فرم",
  "farechase": "FareChase",
  "successfully": "کامیابی سے",
  "obtained": "حاصل کیا",
  "texas": "ٹیکساس",
  "trial": "ٹرائل",
  "court": "عدالت",
  "stopping": "روکنا",
  "selling": "فروخت کرنا",
  "software": "سافٹ ویئر",
  "enables": "قابل بناتا ہے",
  "users": "صارفین",
  "compare": "موازنہ کرنا",
  "online": "آن لائن",
  "fares": "کرایہ",
  "searches": "تلاش کرتا ہے",
  "website": "ویب سائٹ",
  "airline": "ایئر لائن",
  "argued": "استدلال کیا",
  "trespassed": "تجاوز کیا",
  "servers": "سرورز",
  "collected": "جمع کیا",
  "publicly": "عوامی طور پر",
  "available": "دستیاب",
  "data": "ڈیٹا",
  "filed": "دائر کیا",
  "appeal": "اپیل",
  "march": "مارچ",
  "2003": "2003",
  "june": "جون",
  "settle": "تصفیہ کرنا",
  "dropped": "چھوڑ دیا گیا",
  "southwest": "ساؤتھ ویسٹ",
  "also": "بھی",
  "challenged": "چیلنج کیا ہے",
  "practices": "طریقوں",
  "involved": "شامل کیا ہے",
  "both": "دونوں",
  "another": "ایک اور",
  "outtask": "Outtask",
  "legal": "قانونی",
  "claim": "دعویٰ",
  "charged": "الزام لگایا",
  "illegal": "غیر قانونی",
  "example": "مثال",
  "computer": "کمپیوٹر",
  "fraud": "دھوکہ دہی",
  "abuse": "بدسلوکی",
  "led": "کی وجہ سے ہوا ہے",
  "damage": "نقصان",
  "loss": "نقصان",
  "unauthorized": "غیر مجاز",
  "access": "رسائی",
  "site": "سائٹ",
  "constitutes": "تشکیل دیتا ہے",
  "interference": "مداخلت",
  "business": "کاروباری",
  "relations": "تعلقات",
  "trespass": "تجاوز",
  "harmful": "نقصان دہ",
  "breach": "خلاف ورزی",
  "user": "صارف",
  "agreement": "معاہدہ",
  "denied": "انکار کیا",
  "all": "تمام",
  "these": "ان",
  "claims": "دعویٰ",
  "claiming": "دعویٰ کرتے ہوئے",
  "prevailing": "مروجہ",
  "law": "قانون",
  "case": "کیس",
  "should": "ہونا چاہیے",
  "copyright": "کاپی رائٹ",
  "under": "کے تحت",
  "pieces": "ٹکڑے",
  "information": "معلومات",
  "subject": "موضوع",
  "protection": "تحفظ",
  "although": "اگرچہ",
  "never": "کبھی نہیں",
  "resolved": "حل ہوئے",
  "supreme": "سپریم",
  "court": "عدالت",
  "united": "متحدہ",
  "states": "ریاستوں",
  "eventually": "بالآخر",
  "shuttered": "بند کر دیا گیا",
  "parent": "والدین",
  "company": "کمپنی",
  "yahoo": "یاہو",
  "purchased": "خرید لیا گیا",
  "travel": "سفر",
  "expense": "اخراجات",
  "concur": "Concur",
  "2012": "2012",
  "startup": "اسٹارٹ اپ",
  "3taps": "3Taps",
  "scraped": "اسکریپ کیا",
  "classified": "کلاسیفائیڈ",
  "housing": "ہاؤسنگ",
  "ads": "اشتہارات",
  "craigslist": "کریگ لسٹ",
  "sent": "بھیجا",
  "cease-and-desist": "سیز اینڈ ڈیسسٹ",
  "letter": "خط",
  "blocked": "بلاک کر دیا",
  "ip": "IP",
  "addresses": "پتوں",
  "later": "بعد میں",
  "sued": "مقدمہ دائر کیا",
  "held": "قرار دیا",
  "sufficient": "کافی",
  "properly": "مناسب طریقے سے",
  "violated": "خلاف ورزی کی",
  "computer": "کمپیوٹر",
  "fraud": "دھوکہ دہی",
  "abuse": "بدسلوکی",
  "act": "ایکٹ",
  "early": "ابتدائی",
  "decisions": "فیصلے",
  "theories": "نظریات",
  "liability": "ذمہ داری",
  "uniform": "یکساں",
  "difficult": "مشکل",
  "ignore": "نظر انداز کرنا",
  "pattern": "پیٹرن",
  "emerging": "ابھرتا ہوا",
  "prepared": "تیار",
  "protect": "تحفظ",
  "proprietary": "ملکیتی",
  "content": "مواد",
  "commercial": "تجارتی",
  "sites": "سائٹس",
  "uses": "استعمالات",
  "undesirable": "ناپسندیدہ",
  "owners": "مالکان",
  "degree": "حد",
  "protection": "تحفظ",
  "settled": "طے شدہ",
  "depend": "انحصار کرے گا",
  "type": "قسم",
  "made": "کی گئی",
  "scraper": "اسکریپر",
  "amount": "مقدار",
  "copied": "کاپی کی گئی",
  "adversely": "مخالفانہ طور پر",
  "affects": "اثر انداز ہوتا ہے",
  "owner's": "مالک کے",
  "system": "سسٹم",
  "types": "اقسام",
  "manner": "طریقہ",
  "prohibitions": "پابندیاں",
  "conduct": "طرز عمل",
  "while": "جبکہ",
  "law": "قانون",
  "area": "علاقہ",
  "becomes": "بنتا ہے",
  "more": "زیادہ",
  "settled": "طے شدہ",
  "entities": "اداروں",
  "contemplating": "غور کر رہے ہیں",
  "using": "استعمال کرنے کے لیے",
  "programs": "پروگرامز",
  "access": "رسائی حاصل کرنے کے لیے",
  "public": "عوامی",
  "web": "ویب",
  "site": "سائٹ",
  "also": "بھی",
  "consider": "غور کرنا چاہیے",
  "whether": "کہ آیا",
  "action": "عمل",
  "authorized": "مجاز ہے",
  "reviewing": "جائزہ لے کر",
  "terms": "شرائط",
  "use": "استعمال",
  "other": "دیگر",
  "notices": "نوٹس",
  "posted": "پوسٹ کیے گئے",
  "made": "کیے گئے",
  "available": "دستیاب",
  "through": "کے ذریعے",
  "cvent": "Cvent",
  "inc": "Inc.",
  "eventbrite": "Eventbrite",
  "2010": "2010",
  "united": "متحدہ",
  "states": "ریاستوں",
  "district": "ضلعی",
  "court": "عدالت",
  "eastern": "مشرقی",
  "virginia": "ورجینیا",
  "ruled": "فیصلہ کیا",
  "brought": "لائے جانے چاہئیں",
  "users'": "صارفین کی",
  "attention": "توجہ",
  "order": "حکم",
  "browsewrap": "براؤز ریپ",
  "contract": "معاہدہ",
  "license": "لائسنس",
  "enforceable": "قابل نفاذ",
  "2014": "2014",
  "case": "کیس",
  "filed": "دائر کیا گیا",
  "eastern": "مشرقی",
  "pennsylvania": "پنسلوانیا",
  "e-commerce": "ای کامرس",
  "qvc": "QVC",
  "objected": "اعتراض کیا",
  "pinterest-like": "Pinterest جیسی",
  "shopping": "شاپنگ",
  "aggregator": "ایگریگیٹر",
  "resultly's": "Resultly کا",
  "scraping": "اسکریپنگ",
  "real-time": "ریئل ٹائم",
  "pricing": "قیمتوں کا تعین",
  "qvc": "QVC",
  "alleges": "الزام ہے",
  "resultly": "Resultly",
  "excessively": "ضرورت سے زیادہ",
  "crawled": "کرال کیا",
  "retail": "ریٹیل",
  "allegedly": "مبینہ طور پر",
  "sending": "بھیجنا",
  "200-300": "200-300",
  "search": "تلاش",
  "requests": "درخواستیں",
  "minute": "منٹ",
  "sometimes": "کبھی کبھی",
  "up": "تک",
  "36,000": "36,000",
  "caused": "وجہ بنا",
  "crash": "کریش",
  "two": "دو",
  "days": "دن",
  "resulting": "نتیجے میں",
  "lost": "ضائع شدہ",
  "sales": "سیلز",
  "complaint": "شکایت",
  "defendant": "مدعا علیہ",
  "disguised": "چھپایا",
  "crawler": "کرالر",
  "mask": "چھپانا",
  "source": "ماخذ",
  "ip": "IP",
  "address": "ایڈریس",
  "thus": "اس طرح",
  "prevented": "روکا",
  "quickly": "تیزی سے",
  "repairing": "مرمت کرنا",
  "problem": "مسئلہ",
  "particularly": "خاص طور پر",
  "interesting": "دلچسپ",
  "seeking": "تلاش کر رہا ہے",
  "damages": "ہرجانے",
  "unavailability": "عدم دستیابی",
  "claimed": "دعویٰ کیا",
  "caused": "کی وجہ سے ہوا",
  "plaintiff's": "مدعی کی",
  "web": "ویب",
  "site": "سائٹ",
  "period": "مدت",
  "trial": "ٹرائل",
  "terms": "شرائط",
  "use": "استعمال",
  "link": "لنک",
  "displayed": "دکھایا گیا ہے",
  "among": "کے درمیان",
  "all": "تمام",
  "links": "لنکس",
  "bottom": "نیچے",
  "page": "صفحہ",
  "most": "زیادہ تر",
  "sites": "سائٹس",
  "internet": "انٹرنیٹ",
  "ruling": "فیصلہ",
  "contradicts": "متصادم ہے",
  "irish": "آئرش",
  "described": "بیان کیا گیا ہے",
  "below": "نیچے",
  "also": "بھی",
  "rejected": "مسترد کیا",
  "argument": "استدلال",
  "browse-wrap": "براؤز ریپ",
  "restrictions": "پابندیاں",
  "enforceable": "قابل نفاذ",
  "view": "نظر میں",
  "virginia's": "ورجینیا کا",
  "adoption": "اپنانا",
  "uniform": "یکساں",
  "computer": "کمپیوٹر",
  "information": "معلومات",
  "transactions": "ٹرانزیکشنز",
  "act": "ایکٹ",
  "ucita": "UCITA",
  "many": "بہت سے",
  "believed": "مانتے تھے",
  "favor": "حق میں",
  "common": "عام",
  "contracting": "معاہدہ کرنا",
  "practices": "طریقے",
  "facebook": "فیس بک",
  "inc": "Inc.",
  "power": "پاور",
  "ventures": "وینچرز",
  "2012": "2012",
  "district": "ضلعی",
  "court": "عدالت",
  "ruled": "فیصلہ کیا",
  "scrape": "اسکریپ",
  "pages": "صفحات",
  "behalf": "کی طرف سے",
  "user": "صارف",
  "case": "کیس",
  "appeal": "اپیل",
  "electronic": "الیکٹرانک",
  "frontier": "فرنٹیئر",
  "foundation": "فاؤنڈیشن",
  "filed": "دائر کیا",
  "brief": "بریف",
  "asking": "مطالبہ کرتے ہوئے",
  "overturned": "پلٹ دیا جائے",
  "associated": "ایسوسی ایٹڈ",
  "press": "پریس",
  "meltwater": "میلٹ واٹر",
  "u.s.": "یو ایس",
  "holdings": "ہولڈنگز",
  "court": "عدالت",
  "held": "قرار دیا",
  "liable": "ذمہ دار",
  "scraping": "اسکریپنگ",
  "republishing": "دوبارہ شائع کرنا",
  "news": "خبریں",
  "information": "معلومات",
  "from": "سے",
  "but": "لیکن",
  "united": "متحدہ",
  "kingdom": "بادشاہت",
  "favor": "حق میں",
  "ninth": "نواں",
  "circuit": "سرکٹ",
  "ruled": "فیصلہ کیا",
  "did": "نہیں کیا",
  "violate": "خلاف ورزی کرنا",
  "cfaa": "CFAA",
  "hiq": "hiQ",
  "labs": "لیبز",
  "linkedin": "LinkedIn",
  "appealed": "اپیل کی گئی",
  "supreme": "سپریم",
  "court": "عدالت",
  "returned": "واپس بھیجا",
  "reconsider": "دوبارہ غور کرنا",
  "light": "روشنی میں",
  "2021": "2021",
  "decision": "فیصلہ",
  "van": "وین",
  "buren": "بوریان",
  "narrowed": "تنگ کیا",
  "applicability": "قابل اطلاق",
  "review": "جائزہ",
  "upheld": "برقرار رکھا",
  "prior": "سابقہ",
  "internet": "انٹرنیٹ",
  "archive": "آرکائیو",
  "collects": "جمع کرتا ہے",
  "distributes": "تقسیم کرتا ہے",
  "significant": "اہم",
  "number": "تعداد",
  "publicly": "عوامی طور پر",
  "available": "دستیاب",
  "web": "ویب",
  "pages": "صفحات",
  "without": "کے بغیر",
  "being": "ہونے کے",
  "considered": "سمجھا جاتا ہے",
  "violation": "خلاف ورزی",
  "copyright": "کاپی رائٹ",
  "laws": "قوانین",
  "citation": "حوالہ",
  "needed": "ضرورت ہے",
  "european": "یورپی",
  "union": "یونین",
  "february": "فروری",
  "2006": "2006",
  "danish": "ڈینش",
  "maritime": "سمندری",
  "commercial": "تجارتی",
  "court": "عدالت",
  "copenhagen": "کوپن ہیگن",
  "ruled": "فیصلہ کیا",
  "systematic": "منظم",
  "crawling": "کرالنگ",
  "indexing": "انڈیکسنگ",
  "deep": "گہری",
  "linking": "لنکنگ",
  "portal": "پورٹل",
  "ofir.dk": "ofir.dk",
  "real": "حقیقی",
  "estate": "اسٹیٹ",
  "home.dk": "Home.dk",
  "does": "نہیں کرتا",
  "conflict": "تصادم",
  "danish": "ڈینش",
  "law": "قانون",
  "database": "ڈیٹا بیس",
  "directive": "ہدایت",
  "complicated": "پیچیدہ",
  "matters": "معاملات",
  "jurisdiction": "اختیار",
  "ireland's": "آئرلینڈ کی",
  "high": "ہائی",
  "court": "عدالت",
  "delivered": "دیا",
  "verdict": "فیصلہ",
  "illustrates": "مثال پیش کرتا ہے",
  "inchoate": "ابتدائی",
  "state": "حالت",
  "developing": "ترقی پذیر",
  "case": "کیس",
  "ryanair": "ریان ایئر",
  "ltd": "Ltd",
  "billigfluege.de": "Billigfluege.de",
  "gmbh": "GmbH",
  "ireland's": "آئرلینڈ کی",
  "high": "ہائی",
  "court": "عدالت",
  "ruled": "فیصلہ کیا",
  "click-wrap": "کلک ریپ",
  "agreement": "معاہدہ",
  "legally": "قانونی طور پر",
  "binding": "پابند",
  "contrast": "برعکس",
  "findings": "نتائج",
  "united": "متحدہ",
  "states": "ریاستوں",
  "district": "ضلعی",
  "court": "عدالت",
  "eastern": "مشرقی",
  "virginia": "ورجینیا",
  "danish": "ڈینش",
  "maritime": "سمندری",
  "commercial": "تجارتی",
  "justice": "جسٹس",
  "michael": "مائیکل",
  "hanna": "ہنا",
  "ruled": "فیصلہ کیا",
  "hyperlink": "ہائیپر لنک",
  "ryanair's": "ریان ایئر کی",
  "terms": "شرائط",
  "conditions": "ضوابط",
  "plainly": "واضح طور پر",
  "visible": "نظر آنے والا",
  "placing": "رکھنا",
  "onus": "بوجھ",
  "user": "صارف",
  "agree": "متفق ہونا",
  "gain": "حاصل کرنا",
  "access": "رسائی",
  "online": "آن لائن",
  "services": "خدمات",
  "sufficient": "کافی",
  "comprise": "تشکیل دینا",
  "contractual": "معاہدہ کا",
  "relationship": "تعلق",
  "decision": "فیصلہ",
  "appeal": "اپیل",
  "supreme": "سپریم",
  "court": "عدالت",
  "april": "اپریل",
  "30": "30",
  "2020": "2020",
  "french": "فرانسیسی",
  "data": "ڈیٹا",
  "protection": "تحفظ",
  "authority": "اتھارٹی",
  "cnil": "CNIL",
  "released": "جاری کیا",
  "new": "نئی",
  "guidelines": "رہنما اصول",
  "web": "ویب",
  "scraping": "اسکریپنگ",
  "clear": "واضح",
  "publicly": "عوامی طور پر",
  "available": "دستیاب",
  "still": "اب بھی",
  "personal": "ذاتی",
  "cannot": "نہیں کیا جا سکتا",
  "repurposed": "دوبارہ استعمال کیا جا سکتا",
  "without": "کے بغیر",
  "knowledge": "علم",
  "person": "شخص",
  "whom": "جس کا",
  "belongs": "تعلق ہے",
  "finddatalab.com": "FindDataLab.com",
  "2020-06-09": "2020-06-09",
  "can": "سکتے ہیں",
  "you": "آپ",
  "perform": "انجام دیں",
  "new": "نئے",
  "guidelines": "رہنما اصول",
  "medium": "میڈیم",
  "australia": "آسٹریلیا",
  "spam": "اسپام",
  "act": "ایکٹ",
  "2003": "2003",
  "outlaws": "غیر قانونی قرار دیتا ہے",
  "forms": "اقسام",
  "web": "ویب",
  "harvesting": "ہارویسٹنگ",
  "although": "اگرچہ",
  "applies": "لاگو ہوتا ہے",
  "email": "ای میل",
  "addresses": "پتوں",
  "national": "قومی",
  "office": "آفس",
  "information": "معلومات",
  "economy": "معیشت",
  "february": "فروری",
  "overview": "جائزہ",
  "business": "کاروبار",
  "australian": "آسٹریلوی",
  "communications": "کمیونیکیشنز",
  "authority": "اتھارٹی",
  "practical": "عملی",
  "guide": "رہنما",
  "india": "بھارت",
  "leaving": "چھوڑ کر",
  "few": "چند",
  "cases": "کیسز",
  "dealing": "نمٹنے والے",
  "ipr": "IPR",
  "infringement": "خلاف ورزی",
  "indian": "ہندوستانی",
  "courts": "عدالتوں",
  "expressly": "واضح طور پر",
  "ruled": "فیصلہ نہیں کیا ہے",
  "legality": "قانونی حیثیت",
  "web": "ویب",
  "scraping": "اسکریپنگ",
  "however": "تاہم",
  "since": "چونکہ",
  "all": "تمام",
  "common": "عام",
  "forms": "اقسام",
  "electronic": "الیکٹرانک",
  "contracts": "معاہدے",
  "enforceable": "قابل نفاذ",
  "india": "بھارت",
  "violating": "خلاف ورزی کرنا",
  "terms": "شرائط",
  "use": "استعمال",
  "prohibiting": "ممنوع قرار دینا",
  "data": "ڈیٹا",
  "violation": "خلاف ورزی",
  "contract": "معاہدہ",
  "law": "قانون",
  "also": "بھی",
  "information": "انفارمیشن",
  "technology": "ٹیکنالوجی",
  "act": "ایکٹ",
  "2000": "2000",
  "penalizes": "سزا دیتا ہے",
  "unauthorized": "غیر مجاز",
  "access": "رسائی",
  "computer": "کمپیوٹر",
  "resource": "ریسورس",
  "extracting": "نکالنا",
  "methods": "طریقے",
  "prevent": "روکنے کے لیے",
  "administrator": "ایڈمنسٹریٹر",
  "website": "ویب سائٹ",
  "can": "سکتا ہے",
  "various": "مختلف",
  "measures": "اقدامات",
  "stop": "روکنے",
  "slow": "سست کرنے کے لیے",
  "bot": "بوٹ",
  "some": "کچھ",
  "techniques": "تکنیکیں",
  "blocking": "بلاک کرنا",
  "ip": "IP",
  "address": "ایڈریس",
  "either": "یا تو",
  "manually": "دستی طور پر",
  "based": "پر مبنی",
  "criteria": "معیار",
  "geolocation": "جغرافیائی محل وقوع",
  "dnsrbl": "DNSRBL",
  "will": "ہوگا",
  "also": "بھی",
  "browse": "براؤزنگ",
  "from": "سے",
  "disabling": "غیر فعال کرنا",
  "any": "کوئی بھی",
  "web": "ویب",
  "service": "سروس",
  "api": "API",
  "system": "سسٹم",
  "might": "سکتا ہے",
  "expose": "ظاہر کر سکتا ہے",
  "bots": "بوٹس",
  "sometimes": "کبھی کبھی",
  "declare": "اعلان کرتے ہیں",
  "who": "کون",
  "they": "وہ",
  "are": "ہیں",
  "using": "استعمال کرتے ہوئے",
  "user": "صارف",
  "agent": "ایجنٹ",
  "strings": "سٹرنگز",
  "blocked": "بلاک کیا جا سکتا ہے",
  "basis": "بنیاد پر",
  "robots.txt": "robots.txt",
  "googlebot": "googlebot",
  "example": "مثال",
  "other": "دوسرے",
  "make": "بناتے ہیں",
  "no": "کوئی",
  "distinction": "امتیاز",
  "between": "کے درمیان",
  "themselves": "خود",
  "human": "انسانی",
  "browser": "براؤزر",
  "monitoring": "مانیٹرنگ",
  "excess": "اضافی",
  "traffic": "ٹریفک",
  "tools": "اوزار",
  "verify": "تصدیق کرنا",
  "real": "حقیقی",
  "person": "شخص",
  "accessing": "رسائی حاصل کرنا",
  "site": "سائٹ",
  "captcha": "CAPTCHA",
  "coded": "کوڈ کیے جاتے ہیں",
  "explicitly": "واضح طور پر",
  "break": "توڑنا",
  "specific": "مخصوص",
  "patterns": "پیٹرن",
  "employ": "استعمال کر سکتے ہیں",
  "third-party": "تیسرے فریق کی",
  "services": "خدمات",
  "utilize": "استعمال کرتے ہیں",
  "human": "انسانی",
  "labor": "محنت",
  "read": "پڑھنے",
  "respond": "جواب دینے کے لیے",
  "real-time": "ریئل ٹائم",
  "challenges": "چیلنجز",
  "triggered": "ٹرگر کیے جا سکتے ہیں",
  "because": "کیونکہ",
  "making": "کر رہے ہیں",
  "too": "بہت زیادہ",
  "many": "بہت سی",
  "requests": "درخواستیں",
  "short": "مختصر",
  "time": "وقت",
  "using": "استعمال کر رہے ہیں",
  "low-quality": "کم معیار کے",
  "proxies": "پراکسیز",
  "covering": "چھپانا",
  "scraper’s": "اسکریپر کا",
  "fingerprint": "فنگر پرنٹ",
  "properly": "مناسب طریقے سے",
  "commercial": "تجارتی",
  "anti-bot": "اینٹی بوٹ",
  "offer": "پیش کرتے ہیں",
  "anti-scraping": "اینٹی اسکریپنگ",
  "firewalls": "فائر والز",
  "limited": "محدود",
  "detection": "پتہ لگانے کی",
  "capabilities": "صلاحیتیں",
  "however": "تاہم",
  "many": "بہت سے",
  "solutions": "حل",
  "effective": "موثر",
  "locating": "تلاش کرنا",
  "honeypot": "ہنی پاٹ",
  "method": "طریقہ",
  "identify": "شناخت کرنا",
  "ip": "IP",
  "addresses": "پتوں",
  "automated": "خودکار",
  "crawlers": "کرالرز",
  "obfuscation": "ابہام",
  "css": "CSS",
  "sprites": "اسپرائٹس",
  "display": "دکھانے کے لیے",
  "data": "ڈیٹا",
  "telephone": "ٹیلی فون",
  "numbers": "نمبر",
  "email": "ای میل",
  "cost": "قیمت پر",
  "accessibility": "رسائی",
  "screen": "اسکرین",
  "reader": "ریڈر",
  "users": "صارفین",
  "rely": "انحصار کرتے ہیں",
  "consistency": "تسلسل",
  "front-end": "فرنٹ اینڈ",
  "code": "کوڈ",
  "target": "ہدف",
  "website": "ویب سائٹ",
  "adding": "شامل کرنا",
  "small": "چھوٹی",
  "variations": "تبدیلیاں",
  "html/css": "HTML/CSS",
  "surrounding": "ارد گرد",
  "important": "اہم",
  "data": "ڈیٹا",
  "navigation": "نیویگیشن",
  "elements": "عناصر",
  "require": "ضرورت ہوگی",
  "more": "زیادہ",
  "human": "انسانی",
  "involvement": "شمولیت",
  "initial": "ابتدائی",
  "set": "سیٹ اپ",
  "done": "کیا جائے",
  "effectively": "موثر طریقے سے",
  "render": "بنا سکتا ہے",
  "too": "بہت",
  "difficult": "مشکل",
  "scrape": "اسکریپ کرنا",
  "due": "کی وجہ سے",
  "diminished": "کم شدہ",
  "ability": "صلاحیت",
  "automate": "خودکار کرنا",
  "process": "عمل",
  "declare": "اعلان کر سکتے ہیں",
  "crawling": "کرالنگ",
  "allowed": "اجازت ہے",
  "robots.txt": "robots.txt",
  "file": "فائل",
  "allow": "اجازت دیں",
  "partial": "جزوی",
  "access": "رسائی",
  "limit": "محدود کریں",
  "crawl": "شرح",
  "specify": "مخصوص کریں",
  "optimal": "بہترین",
  "time": "وقت",
  "see": "دیکھیں",
  "also": "بھی",
  "archive.today": "Archive.today",
  "comparison": "موازنہ",
  "feed": "فیڈ",
  "aggregators": "ایگریگیٹرز",
  "data": "ڈیٹا",
  "scraping": "اسکریپنگ",
  "wrangling": "ورینگلنگ",
  "importer": "امپورٹر",
  "job": "جاب",
  "wrapping": "ریپنگ",
  "knowledge": "علم",
  "extraction": "نکالنا",
  "opensocial": "OpenSocial",
  "scraper": "اسکریپر",
  "site": "سائٹ",
  "fake": "جعلی",
  "news": "خبریں",
  "website": "ویب سائٹ",
  "spamdexing": "اسپیمڈیکسنگ",
  "domain": "ڈومین",
  "name": "نام",
  "drop": "ڈراپ",
  "list": "فہرست",
  "text": "متن",
  "corpus": "کارپس",
  "web": "ویب",
  "archiving": "آرکائیو کرنا",
  "crawler": "کرالر",
  "offline": "آف لائن",
  "reader": "ریڈر",
  "link": "لنک",
  "farm": "فارم",
  "blog": "بلاگ",
  "network": "نیٹ ورک",
  "search": "تلاش",
  "engine": "انجن",
  "references": "حوالہ جات",
  "retrieved": "حاصل کیا گیا",
  "from": "سے",
  "w/index.php?title=web_scraping&oldid=1297146564": "w/index.php?title=web_scraping&oldid=1297146564",
  "perfect": "کامل"
};

const translateToUrdu = (text) => {
  if (!text) return '';
  // Simple word-by-word translation. More complex NLP would be needed for accurate sentence translation.
  return text.split(/\b/).map(word => {
    const lowerCaseWord = word.toLowerCase();
    return englishToUrduDictionary[lowerCaseWord] || word;
  }).join('');
};

const App = () => {
  const [blogUrl, setBlogUrl] = useState('');
  const [summary, setSummary] = useState('');
  const [urduSummary, setUrduSummary] = useState(''); // NEW: State for Urdu summary
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');
  const [isMessageModalOpen, setIsMessageModalOpen] = useState(false);
  const [fullText, setFullText] = useState(''); // State to store the full scraped text

  // Function to show a custom message modal
  const showMessage = (msg) => {
    setMessage(msg);
    setIsMessageModalOpen(true);
  };

  // Function to close the custom message modal
  const closeMessageModal = () => {
    setIsMessageModalOpen(false);
    setMessage('');
  };

  // Function to handle summary generation
  const handleSummarize = async () => {
    if (blogUrl.trim() === '') {
      showMessage("Please enter a blog URL.");
      return;
    }

    setLoading(true);
    setSummary(''); // Clear previous summary
    setUrduSummary(''); // Clear previous Urdu summary
    setFullText(''); // Clear previous full text

    try {
      // --- Step 1: Fetch Full Text via Local Node.js API Server ---
      const scrapeResponse = await fetch('http://localhost:3001/api/scrape', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ url: blogUrl }),
      });

      if (!scrapeResponse.ok) {
        const errorData = await scrapeResponse.json();
        throw new Error(`Scraping failed: ${errorData.message || scrapeResponse.statusText}`);
      }

      const { fullText: scrapedContent } = await scrapeResponse.json();
      setFullText(scrapedContent); // Store the actual scraped text

      // --- Step 2: Simulate AI Summary (static logic as per request) ---
      // Taking the first few sentences as a "summary".
      const simulatedSummary = scrapedContent.split('. ').slice(0, 3).join('. ') + '.';
      setSummary(simulatedSummary);

      // --- Step 3: Save Summary to Supabase; Simulate Full Text Save to MongoDB ---
      // Ensure Supabase URL and Anon Key are correctly loaded from environment variables
      if (!SUPABASE_URL || !SUPABASE_ANON_KEY || SUPABASE_URL === 'undefined' || SUPABASE_ANON_KEY === 'undefined') {
        throw new Error("Supabase URL or Anon Key is not configured. Please check your .env file (for local) or Vercel environment variables (for deployment).");
      }

      const { data, error } = await supabase
        .from('summaries') // Your Supabase table name
        .insert([
          { url: blogUrl, summary_text: simulatedSummary } // Only saving summary to Supabase
        ]);

      if (error) {
        console.error('Error saving summary to Supabase:', error);
        showMessage('Failed to save summary to database. Please check console.');
      } else {
        console.log('Summary saved to Supabase:', data);
        // Simulate saving full text to MongoDB
        console.log('Simulating save of full text to MongoDB:', scrapedContent.substring(0, 100) + '...');
        showMessage('Blog summarised and saved successfully (summary to Supabase, full text simulated to MongoDB)!'); // Success message
      }

    } catch (error) {
      console.error("Error during summarization process:", error);
      showMessage(`An error occurred: ${error.message}. Please check console.`);
    } finally {
      setLoading(false);
    }
  };

  // NEW: Function to handle Urdu translation (Re-added as per project features)
  const handleTranslateToUrdu = () => {
    if (summary.trim() === '') {
      showMessage("Please generate a summary first before translating.");
      return;
    }
    const translatedText = translateToUrdu(summary);
    setUrduSummary(translatedText);
    showMessage("Summary translated to Urdu!");
  };

  return (
    <div className="min-h-screen bg-gray-950 text-gray-100 flex items-center justify-center p-4 font-inter">
      <div className="w-full max-w-2xl bg-gray-800 rounded-2xl shadow-2xl p-8 space-y-8 border border-gray-700">
        <h1 className="text-4xl md:text-5xl font-extrabold text-center text-purple-400 mb-6 drop-shadow-lg">
          Blog Summariser
        </h1>

        {/* URL Input Section */}
        <div className="space-y-5">
          <label htmlFor="blog-url-input" className="block text-base font-medium text-gray-300">
            Enter Blog URL:
          </label>
          <input
            id="blog-url-input"
            type="url"
            value={blogUrl}
            onChange={(e) => setBlogUrl(e.target.value)}
            placeholder="e.g., https://example.com/blog-post"
            className="flex h-12 w-full rounded-lg border border-gray-600 bg-gray-900 px-4 py-2 text-base placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent disabled:cursor-not-allowed disabled:opacity-50 text-gray-200 shadow-md transition-all duration-200"
            disabled={loading}
          />
          <div className="flex flex-col sm:flex-row gap-4 mt-4">
            <button
              onClick={handleSummarize}
              className="flex-1 inline-flex items-center justify-center rounded-lg text-base font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-600 focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none ring-offset-gray-900 bg-purple-700 text-white hover:bg-purple-800 h-12 px-6 py-3 shadow-lg transform hover:scale-105 active:scale-95 duration-200"
              disabled={loading}
            >
              {loading ? 'Summarising...' : 'Summarise Blog'}
            </button>
            {/* Re-added "Translate to Urdu" button */}
            <button
              onClick={handleTranslateToUrdu}
              className="flex-1 inline-flex items-center justify-center rounded-lg text-base font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none ring-offset-gray-900 bg-blue-700 text-white hover:bg-blue-800 h-12 px-6 py-3 shadow-lg transform hover:scale-105 active:scale-95 duration-200"
              disabled={loading || !summary} // Disable if loading or no summary
            >
              Translate to Urdu 🌐
            </button>
          </div>
        </div>

        {/* Summary Display Section */}
        {loading && (
          <div className="text-center text-gray-400 mt-8 text-lg animate-pulse">
            Fetching and summarising, please wait...
          </div>
        )}

        {!loading && summary && (
          <div className="space-y-4 mt-8 p-6 bg-gray-700 rounded-xl shadow-inner border border-gray-600">
            <h2 className="text-2xl font-bold text-gray-200 text-center mb-4">Summary (English):</h2>
            <div className="rounded-lg border border-gray-600 bg-gray-900 p-5 shadow-md">
              <p className="text-gray-300 leading-relaxed text-lg">{summary}</p>
            </div>
          </div>
        )}

        {/* Re-added Urdu Summary Display Section */}
        {!loading && urduSummary && (
          <div className="space-y-4 mt-8 p-6 bg-gray-700 rounded-xl shadow-inner border border-gray-600">
            <h2 className="text-2xl font-bold text-gray-200 text-center mb-4">خلاصہ (اردو):</h2>
            <div className="rounded-lg border border-gray-600 bg-gray-900 p-5 shadow-md">
              <p className="text-gray-300 leading-relaxed text-lg text-right font-['Noto_Nastaliq_Urdu']">{urduSummary}</p> {/* text-right for Urdu */}
            </div>
          </div>
        )}

        {/* Full Text Display (Optional for debugging/verification) */}
        {!loading && fullText && (
          <div className="space-y-4 mt-8 p-6 bg-gray-700 rounded-xl shadow-inner border border-gray-600">
            <h2 className="text-2xl font-bold text-gray-200 text-center mb-4">Full Scraped Text:</h2>
            <div className="rounded-lg border border-gray-600 bg-gray-900 p-5 shadow-md max-h-80 overflow-y-auto">
              <pre className="text-gray-400 text-sm whitespace-pre-wrap font-mono">{fullText}</pre>
            </div>
          </div>
        )}

        {/* Message Modal */}
        {isMessageModalOpen && (
          <div className="fixed inset-0 bg-black bg-opacity-70 flex items-center justify-center z-50 p-4 backdrop-blur-sm">
            <div className="bg-gray-800 rounded-xl p-8 shadow-2xl max-w-md w-full space-y-6 border border-gray-700 transform scale-100 animate-fade-in">
              <h3 className="text-2xl font-bold text-gray-100 text-center">Notification</h3>
              <p className="text-gray-300 text-center text-lg">{message}</p>
              <button
                onClick={closeMessageModal}
                className="w-full inline-flex items-center justify-center rounded-lg text-base font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-600 focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none ring-offset-gray-900 bg-purple-700 text-white hover:bg-purple-800 h-12 px-6 py-3 shadow-lg transform hover:scale-105 active:scale-95 duration-200"
              >
                OK
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default App;
